=== BestJex/tis-neptune/terminator-job-trigger-test/solrschema.dtd
<!ELEMENT schema (types+,fields+,uniqueKey,defaultSearchField,similarity?,solrQueryParser,copyField*)>

<!ATTLIST schema name CDATA #REQUIRED>
<!ATTLIST schema version CDATA #REQUIRED>

<!ELEMENT types (fieldType+)>
<!ELEMENT fieldType (analyzer*)>

<!ATTLIST fieldType name CDATA #REQUIRED>
<!ATTLIST fieldType class CDATA #REQUIRED>
<!ATTLIST fieldType positionIncrementGap CDATA #IMPLIED> 
<!ATTLIST fieldType sortMissingLast (true|false) "true">
<!ATTLIST fieldType omitNorms (true|false) "true">
<!ATTLIST fieldType precisionStep CDATA #IMPLIED>
<!ATTLIST fieldType autoGeneratePhraseQueries (true|false) #IMPLIED>
<!ATTLIST fieldType tokenized (true|false) #IMPLIED>
<!ATTLIST fieldType omitTermFreqAndPositions (true|false) #IMPLIED>
<!ATTLIST fieldType omitPositions (true|false) #IMPLIED>



<!ELEMENT analyzer (tokenizer*,filter*)>
<!ATTLIST analyzer 
  type (index|query) #IMPLIED
  class CDATA        #IMPLIED>

<!ELEMENT tokenizer EMPTY>
<!ATTLIST tokenizer 
   class CDATA #REQUIRED
   group CDATA #IMPLIED
   pattern CDATA #IMPLIED
   isMaxWordLength (true|false) #IMPLIED>
   

<!ELEMENT filter EMPTY>
<!ATTLIST filter class CDATA #REQUIRED>

<!ELEMENT uniqueKey (#PCDATA)>
<!ELEMENT defaultSearchField (#PCDATA)>

<!ELEMENT similarity (str*)>
<!ATTLIST similarity class CDATA #REQUIRED>

<!ELEMENT str (#PCDATA)>
<!ATTLIST str name CDATA #REQUIRED>


<!ELEMENT solrQueryParser EMPTY>
<!ATTLIST solrQueryParser defaultOperator (OR|AND) #REQUIRED>

<!ELEMENT fields (field|dynamicField)+>
<!ELEMENT field  EMPTY>
<!ATTLIST field  name CDATA #REQUIRED>
<!ATTLIST field  type CDATA #REQUIRED>
<!ATTLIST field  indexed (true|false) #IMPLIED>
<!ATTLIST field  stored (true|false) #IMPLIED>
<!ATTLIST field  multiValued (true|false) #IMPLIED>
<!ATTLIST field  required (true|false) #IMPLIED>
<!ATTLIST field  default CDATA #IMPLIED>

<!ELEMENT dynamicField EMPTY>
<!ATTLIST dynamicField  name CDATA #REQUIRED>
<!ATTLIST dynamicField  type CDATA #REQUIRED>
<!ATTLIST dynamicField  indexed (true|false) #IMPLIED>
<!ATTLIST dynamicField  stored (true|false) #IMPLIED>
<!ATTLIST dynamicField  multiValued (true|false) #IMPLIED>
<!ATTLIST dynamicField  required (true|false) #IMPLIED>

<!ELEMENT copyField EMPTY>
<!ATTLIST copyField  source CDATA #REQUIRED>
<!ATTLIST copyField  dest CDATA #REQUIRED>

=== BestJex/tis-neptune/terminator-job-trigger-test/src/test/resources/schema3.xml
<?xml version="1.0" ?>

		<!DOCTYPE schema PUBLIC ""
		"http://terminator.admin.taobao.org:9999/dtd/solrschema.dtd">
	<!--
		<!DOCTYPE schema SYSTEM
		"D:\\j2ee_solution\\mvn_test\\terminator-job-trigger-test\\solrschema.dtd">
	-->
<schema name="search4taodan" version="1.1">
	<types>
		<fieldType name="string_pd" class="solr.TextField"
			sortMissingLast="true" omitNorms="true">
			<analyzer class="net.paoding.analysis.analyzer.PaodingAnalyzer"></analyzer>
		</fieldType>
		<fieldType name="int" class="solr.IntField" omitNorms="true" />
		<fieldType name="short" class="solr.ShortField" omitNorms="true" />
		<fieldType name="sint" class="solr.SortableIntField"
			omitNorms="true" />
		<fieldType name="long" class="solr.LongField" omitNorms="true" />
		<fieldType name="slong" class="solr.SortableLongField"
			tokenized="false" omitNorms="true" omitTermFreqAndPositions="true" />
		<fieldType name="tlong" class="solr.TrieLongField"
			precisionStep="8" omitNorms="true" positionIncrementGap="0" />
		<fieldType name="srlong"
			class="com.taobao.terminator.core.fieldx.SLongRangeField" tokenized="false"
			omitNorms="true" omitTermFreqAndPositions="true" />
		<fieldType name="tint" class="solr.TrieIntField"
			precisionStep="8" omitNorms="true" positionIncrementGap="0" />
	</types>
	<fields>
		<field name="id" type="tlong" indexed="true" stored="true"
			multiValued="false" required="true" />
		<field name="userId" type="slong" indexed="true" stored="true"
			multiValued="false" />
		<field name="itemId" type="long" indexed="true" stored="true"
			multiValued="false" />
		<field name="categoryId" type="long" indexed="true" stored="true"
			multiValued="false" />
		<field name="topCategoryId" type="long" indexed="true" stored="true"
			multiValued="false" />
		<field name="buyState" type="int" indexed="true" stored="true"
			multiValued="false" />
		<field name="showFlag" type="int" indexed="true" stored="true"
			multiValued="false" />
		<field name="gmtCreate" type="tlong" indexed="true" stored="true"
			multiValued="false" />
		<field name="gmtModified" type="tlong" indexed="true" stored="true"
			multiValued="false" />
		<field name="imgQuality" type="sint" indexed="true" stored="true"
			multiValued="false" />
		<field name="source" type="string_pd" indexed="true" stored="true"
			multiValued="false" />
		<field name="_SFS_" type="slong" indexed="true" stored="true"
			multiValued="false" default="categoryId:L,imgQuality:S,gmtModified:L" />
	</fields>
	<!-- field to use to determine and enforce document uniqueness. -->
	<uniqueKey>id</uniqueKey>

	<!--
		field for the QueryParser to use when an explicit fieldname is absent
	-->
	<defaultSearchField>id</defaultSearchField>
	<similarity
		class="com.taobao.terminator.service.payload.PayloadSimilarityFactory">
		<str name="1_categoryId">LONG</str>
		<str name="2_imgQuality">SHORT</str>
		<str name="3_gmtModified">LONG</str>
	</similarity>


	<!-- SolrQueryParser configuration: defaultOperator="AND|OR" -->
	<solrQueryParser defaultOperator="OR" />
</schema>

=== BestJex/tis-neptune/terminator-job-trigger-test/src/test/resources/solrschema.xml
<?xml version="1.0" ?>
 <!DOCTYPE schema PUBLIC "" "http://terminator.admin.taobao.org:9999/dtd/solrschema.dtd">
<schema name="example core" version="1.1">
	<types>
		<fieldType name="string" class="solr.TextField"
			sortMissingLast="true"></fieldType>

		<fieldType name="int" class="solr.TrieIntField"
			precisionStep="0" positionIncrementGap="0" />

		<fieldType name="tlong" class="solr.TrieLongField"
			precisionStep="8" omitNorms="true" positionIncrementGap="0" />

		<fieldType name="sint" class="solr.SortableIntField"
			sortMissingLast="true" omitNorms="true" />

		<fieldType name="slong" class="solr.SortableLongField"
			sortMissingLast="true" omitNorms="true" />

		<fieldType name="string_ws" class="solr.TextField"
			positionIncrementGap="100">
			<analyzer>
				<tokenizer class="solr.WhitespaceTokenizerFactory" />
			</analyzer>
		</fieldType>

		<fieldType name="string_sd" class="solr.TextField"
			sortMissingLast="true" omitNorms="true">
			<analyzer type="index">
				<tokenizer class="solr.StandardTokenizerFactory" />
				<filter class="solr.ChineseFilterFactory" />
				<filter class="solr.LowerCaseFilterFactory" />
			</analyzer>
			<analyzer type="query">
				<tokenizer class="solr.StandardTokenizerFactory" />
				<filter class="solr.ChineseFilterFactory" />
				<filter class="solr.LowerCaseFilterFactory" />
			</analyzer>

		</fieldType>

		<fieldType name="tint" class="solr.TrieIntField"
			precisionStep="8" omitNorms="true" positionIncrementGap="0" />
		<fieldType name="tfloat" class="solr.TrieFloatField"
			precisionStep="8" omitNorms="true" positionIncrementGap="0" />
		<fieldType name="sfloat" class="solr.SortableFloatField"
			sortMissingLast="true" omitNorms="true" />

	</types>

	<fields>
		<field name="id" type="slong" indexed="true" stored="true"
			multiValued="false" required="true" />
		<field name="userId" type="slong" indexed="true" stored="true"
			multiValued="false" />
		<field name="userNick" type="string" indexed="true" stored="true"
			multiValued="false" />
		<field name="title" type="string_sd" indexed="true" stored="true"
			multiValued="false" />
		<field name="contentKey" type="string" indexed="true" stored="true"
			multiValued="false" />
		<field name="coverPicpath" type="string" indexed="true" stored="true"
			multiValued="false" />
		<field name="itemId" type="string" indexed="true" stored="true"
			multiValued="false" />
		<field name="gmtCreated" type="slong" indexed="true" stored="true"
			multiValued="false" />
		<field name="gmtModified" type="slong" indexed="true" stored="true"
			multiValued="false" />
		<field name="tag" type="string_sd" indexed="true" stored="true"
			multiValued="false" />
		<field name="aScore" type="sfloat" indexed="true" stored="true"
			multiValued="false" />
		<field name="count" type="int" indexed="true" stored="true"
			multiValued="false" />
		<field name="feedId" type="string" stored="true" multiValued="false" />
		<field name="summary" type="string_sd" indexed="true" stored="true"
			multiValued="false" />
		<field name="status" type="int" indexed="true" stored="true"
			multiValued="false" />

		<dynamicField name="*-t" type="text_com" stored="false"
			indexed="true" />

	</fields>

	<uniqueKey>id</uniqueKey>
	<defaultSearchField>id</defaultSearchField>

	<similarity class="com.taobao.terminator.core.solrx.PayloadSimilarity">
		<str name="func">max</str>
	</similarity>

	<solrQueryParser defaultOperator="OR" />
	<copyField source="prov" dest="location" />
</schema>

=== BestJex/tis-neptune/terminator-job-trigger-test/src/test/resources/test_scheam.xml
<?xml version="1.0" ?>
	<!--
		<!DOCTYPE schema PUBLIC ""
		"http://10.232.136.79:8080/doc/solrschema.dtd">
	-->
 <!DOCTYPE schema PUBLIC "" "http://terminator.admin.taobao.org:9999/dtd/solrschema.dtd">
<schema name="search4barbarian" version="1.1">
	<types>

		<fieldType name="text_paoding" class="solr.TextField"
			sortMissingLast="true" omitNorms="true" autoGeneratePhraseQueries="false">
			<analyzer class="net.paoding.analysis.analyzer.PaodingAnalyzer" />
		</fieldType>

		<fieldType name="text_sem" class="solr.TextField"
			positionIncrementGap="100" autoGeneratePhraseQueries="false">
			<analyzer>
				<tokenizer class="solr.PatternTokenizerFactory" pattern="[^;]+"
					group="0" />
			</analyzer>
		</fieldType>

		<fieldType name="tdouble" class="solr.TrieDoubleField"
			precisionStep="8" omitNorms="true" positionIncrementGap="0" />

		<fieldType name="text_ws" class="solr.TextField"
			positionIncrementGap="100" autoGeneratePhraseQueries="false">
			<analyzer>
				<tokenizer class="solr.WhitespaceTokenizerFactory" />
			</analyzer>
		</fieldType>

		<fieldType name="tfloat" class="solr.TrieFloatField"
			omitNorms="true" />

		<fieldType name="string" class="solr.TextField"
			sortMissingLast="true" omitNorms="true" />
		<fieldType name="tlong" class="solr.TrieLongField"
			precisionStep="0" omitNorms="true" positionIncrementGap="0" />
		<fieldType name="long" class="solr.LongField" omitNorms="true" />
		<fieldType name="int" class="solr.IntField" omitNorms="true" />
		<fieldType name="short" class="solr.ShortField" omitNorms="true" />
		<fieldType name="slong" class="solr.SortableLongField"
			omitNorms="true" />
		<fieldType name="sdouble" class="solr.SortableDoubleField"
			omitNorms="true" />
	</types>
	<fields>

		<field name="item_title" type="text_paoding" indexed="true"
			stored="true" />
		<field name="item_id" type="long" indexed="true" stored="true"
			required="true" />
		<field name="reserve_price" type="tdouble" indexed="true"
			stored="true" />
		<field name="price" type="tdouble" indexed="true" stored="true" />
		<field name="deal_count" type="tlong" indexed="true" stored="true" />
		<field name="appraise_count" type="tlong" indexed="true" stored="true" />
		<field name="seller_id" type="long" indexed="false" stored="true" />
		<field name="division_desc" type="text_ws" indexed="true"
			stored="true" />
		<field name="tags" type="text_sem" indexed="true" stored="true" />
		<field name="shop_rate" type="tfloat" indexed="true" stored="true" />

	</fields>
	
	<uniqueKey>item_id</uniqueKey>
	<defaultSearchField>item_title</defaultSearchField>
	<solrQueryParser defaultOperator="OR" />
</schema>
